[project]
name = "conftamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Patrick Lau", email = "patricklyc@berkeley.edu" }]
dependencies = [
  "igraph>=1.0.0",
  "pydantic>=2.13.4",
  "typer>=0.27.1",
]

[project.scripts]
conftamer = "conftamer.main:app"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
